name: mern-setup


services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server


  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - database

        
  database:
    image: mongo
    container_name: mongo_database
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db


  #database:
  #  image: postgres:17.2-alpine3.21
  #  container_name: pg_database
  #  ports:
  #    - 5432:5432
  #  #restart: always
  #  environment:
  #    POSTGRES_PASSWORD: test12345
  #  volumes:
  #    - ./postgres_data:/var/lib/postgresql/data


  #database_browser:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin4
  #  ports:
  #    - 80:80
  #  #restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@domain.com
  #    PGADMIN_DEFAULT_PASSWORD: password
  #  volumes:
  #    - ./pgadmin_data:/var/lib/pgadmin
  #  depends_on:
  #    - database

